# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'


  - task: SynopsysSecurityScan@1
  displayName: 'Black Duck Full Scan'
  condition: not(eq(variables['Build.Reason'], 'PullRequest'))
  env:
    DETECT_PROJECT_NAME: $(Build.Repository.Name)
    DETECT_PROJECT_VERSION_NAME: $(Build.SourceBranchName)
    DETECT_CODE_LOCATION_NAME: $(Build.Repository.Name)-$(Build.SourceBranchName)
  inputs:
    scanType: blackduck
    bridge_blackduck_url: '$(BLACKDUCK_URL)'
    bridge_blackduck_token: '$(BLACKDUCK_API_TOKEN)'
    bridge_blackduck_scan_full: true
    bridge_blackduck_scan_failure_severities: 'BLOCKER'
 
- task: SynopsysSecurityScan@1
  displayName: 'Black Duck PR Scan'
  condition: eq(variables['Build.Reason'], 'PullRequest')
  env:
    DETECT_PROJECT_NAME: $(Build.Repository.Name)
    DETECT_PROJECT_VERSION_NAME: $(System.PullRequest.targetBranchName)
    DETECT_CODE_LOCATION_NAME: $(Build.Repository.Name)-$(System.PullRequest.targetBranchName)
  inputs:
    scanType: blackduck
    bridge_blackduck_url: '$(BLACKDUCK_URL)'
    bridge_blackduck_token: '$(BLACKDUCK_API_TOKEN)'
    bridge_blackduck_scan_full: false
    bridge_blackduck_automation_prcomment: true
    azure_token: $(System.AccessToken)
 
- task: ArchiveFiles@2
  displayName: 'Copy Log Files'
  condition: succeededOrFailed()
  enabled: false
  inputs:
    rootFolderOrFile: .bridge
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/bridge-logs.zip'
 
- task: PublishBuildArtifacts@1
  displayName: 'Publish Log Files'
  condition: succeededOrFailed()
  enabled: false
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'logs'