name: Detect Wrapper

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple detect_wrapper
      - name: Run Detect_Wrapper
        run: |
          detect_wrapper --blackduck.url=https://poc39.blackduck.synopsys.com \
          --blackduck.api.token=MmQ4OTdlYWQtNDBkMi00ZDI3LWFkNTUtZmQyYWZmYzY0NWM3OmZkMWZkYzhkLTc5NjktNGYxZS04ODBlLWMxYTUzOWMxZjA3NA== \
          --blackduck.trust.cert=true --detect.project.name=newdh --detect.tools=DETECTOR --wrapper.report_html=test.html \
          --wrapper.auto_last_scan --wrapper.report_text --wrapper.junit_xml=out.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '**/out.xml'
          check_name: 'Black Duck SCA Scan Results'
          github_token: ${{ secrets.GITHUB_TOKEN }}
